swagger: "2.0"
info:
  description: PingData Configuration API - OpenAPI 3.0
  title: PingData Configuration API
  version: "9.2.0.0"
externalDocs:
  description: PingDirectory Configuration API Docs
  url: https://docs.pingidentity.com/r/en-us/pingdirectory-92/pd_ds_use_config_api
basePath: /config
securityDefinitions:
  basicAuth:
    type: "basic"
security:
- basicAuth: []
produces:
- application/json
paths:
  /ResourceTypes:
    get:
      summary: List all sub-paths for the Configuration API
      operationId: get-resource-types
      responses:
        "200":
          description: Successful operation
          schema:
            $ref: '#/definitions/get-resource-types-response'
        "400":
          description: The request contents are incorrectly formatted or the request was made for an invalid API version.
        "401":
          description: The requester cannot be authenticated
        "403":
          description: The requester does not have the required privileges or another constraint failed, such as attempting to delete an edit-only object.
        "415":
          description: The request is such that the Accept header does not indicate that JSON is an acceptable format for a response.
        "500":
          description: The server encountered an unexpected error.
      tags:
      - list-resource-types
  /attribute-syntaxes:
    get:
      summary: Returns a list of all Attribute Syntax objects
      operationId: list-attribute-syntaxes
      parameters:
      - $ref: '#/parameters/filter'
      - $ref: '#/parameters/sortBy'
      - $ref: '#/parameters/sortOrder'
      - $ref: '#/parameters/startIndex'
      - $ref: '#/parameters/count'
      - $ref: '#/parameters/attributes'
      - $ref: '#/parameters/excludeAttributes'
      responses:
        "200":
          description: Successful operation
          schema:
            $ref: '#/definitions/attribute-syntax-list-response'
        "204":
          description: The requested operation succeeded and no further information has been provided, such as in the case of a DELETE operation.
        "400":
          description: The request contents are incorrectly formatted or the request was made for an invalid API version.
        "401":
          description: The requester cannot be authenticated
        "403":
          description: The requester does not have the required privileges or another constraint failed, such as attempting to delete an edit-only object.
        "404":
          description: The requested path does not refer to an existing object or object relation.
        "409":
          description: The requested operation could not be performed due to the current state of the configuration. For example, an attempt was made to create an object that already exists or an attempt was made to delete an object that is referred to by another object.
        "415":
          description: The request is such that the Accept header does not indicate that JSON is an acceptable format for a response.
        "500":
          description: The server encountered an unexpected error.
      tags:
      - attribute-syntax
  /attribute-syntaxes/{attribute-syntax-name}:
    get:
      operationId: get-attribute-syntax
      summary: Returns a single Attribute Syntax
      parameters:
      - $ref: '#/parameters/attributes'
      - $ref: '#/parameters/excludeAttributes'
      - description: Name of the Attribute Syntax
        in: path
        name: attribute-syntax-name
        required: true
        type: string
      responses:
        "200":
          description: Successful operation
          schema:
            $ref: '#/definitions/attribute-syntax-response'
        "204":
          description: The requested operation succeeded and no further information has been provided, such as in the case of a DELETE operation.
        "400":
          description: The request contents are incorrectly formatted or the request was made for an invalid API version.
        "401":
          description: The requester cannot be authenticated
        "403":
          description: The requester does not have the required privileges or another constraint failed, such as attempting to delete an edit-only object.
        "404":
          description: The requested path does not refer to an existing object or object relation.
        "409":
          description: The requested operation could not be performed due to the current state of the configuration. For example, an attempt was made to create an object that already exists or an attempt was made to delete an object that is referred to by another object.
        "415":
          description: The request is such that the Accept header does not indicate that JSON is an acceptable format for a response.
        "500":
          description: The server encountered an unexpected error.
      tags:
      - attribute-syntax
    put:
      operationId: put-attribute-syntax
      summary: Update an existing Attribute Syntax by name, replacing any attributes specified in the request body
      parameters:
      - $ref: '#/parameters/attributes'
      - $ref: '#/parameters/excludeAttributes'
      - $ref: '#/parameters/applyChangeTo'
      - description: Name of the Attribute Syntax
        in: path
        name: attribute-syntax-name
        required: true
        type: string
      - name: body
        in: body
        schema:
          $ref: '#/definitions/attribute-syntax-properties'
        description: Attributes to replace in the Attribute Syntax
        required: true
      responses:
        "200":
          description: Successful operation
          schema:
            $ref: '#/definitions/attribute-syntax-response-with-messages'
        "204":
          description: The requested operation succeeded and no further information has been provided, such as in the case of a DELETE operation.
        "400":
          description: The request contents are incorrectly formatted or the request was made for an invalid API version.
        "401":
          description: The requester cannot be authenticated
        "403":
          description: The requester does not have the required privileges or another constraint failed, such as attempting to delete an edit-only object.
        "404":
          description: The requested path does not refer to an existing object or object relation.
        "409":
          description: The requested operation could not be performed due to the current state of the configuration. For example, an attempt was made to create an object that already exists or an attempt was made to delete an object that is referred to by another object.
        "415":
          description: The request is such that the Accept header does not indicate that JSON is an acceptable format for a response.
        "500":
          description: The server encountered an unexpected error.
      tags:
      - attribute-syntax
    patch:
      operationId: patch-attribute-syntax
      summary: Update an existing Attribute Syntax by name, using a SCIM patch request
      parameters:
      - $ref: '#/parameters/attributes'
      - $ref: '#/parameters/excludeAttributes'
      - $ref: '#/parameters/applyChangeTo'
      - description: Name of the Attribute Syntax
        in: path
        name: attribute-syntax-name
        required: true
        type: string
      - name: body
        in: body
        schema:
          $ref: '#/definitions/patch-request'
        description: SCIM operations to apply to the Attribute Syntax
        required: true
      responses:
        "200":
          description: Successful operation
          schema:
            $ref: '#/definitions/attribute-syntax-response-with-messages'
        "204":
          description: The requested operation succeeded and no further information has been provided, such as in the case of a DELETE operation.
        "400":
          description: The request contents are incorrectly formatted or the request was made for an invalid API version.
        "401":
          description: The requester cannot be authenticated
        "403":
          description: The requester does not have the required privileges or another constraint failed, such as attempting to delete an edit-only object.
        "404":
          description: The requested path does not refer to an existing object or object relation.
        "409":
          description: The requested operation could not be performed due to the current state of the configuration. For example, an attempt was made to create an object that already exists or an attempt was made to delete an object that is referred to by another object.
        "415":
          description: The request is such that the Accept header does not indicate that JSON is an acceptable format for a response.
        "500":
          description: The server encountered an unexpected error.
      tags:
      - attribute-syntax

parameters:
  filter:
    in: query
    name: filter
    description: "SCIM filter"
    required: false
    type: string
  sortBy:
    in: query
    name: sortBy
    description: "Specifies a property value by which to sort"
    required: false
    type: string
  sortOrder:
    in: query
    name: sortOrder
    description: "Specifies either ascending or descending alphabetical order"
    required: false
    type: string
    enum:
    - "ascending"
    - "descending"
  startIndex:
    in: query
    name: startIndex
    description: "1-based index of the first result to return"
    required: false
    type: number
  count:
    in: query
    name: count
    description: "Indicates the number of results per page"
    required: false
    type: number
  attributes:
    in: query
    name: attributes
    description: "Comma-separated list of attributes to include in the response"
    required: false
    type: string
  excludeAttributes:
    in: query
    name: excludeAttributes
    description: "Comma-separated list of attributes to exclude from the response"
    required: false
    type: string
  applyChangeTo:
    in: query
    name: applyChangeTo
    description: "Specify whether to apply this configuration change to a single server or the whole server group. This does not apply to mirrored subtree objects"
    required: false
    type: string
    enum:
    - "singleServer"
    - "serverGroup"
definitions:
  get-resource-types-response:
    type: object
    properties:
      schemas:
        type: array
        items:
          type: string
          enum:
          - "urn:ietf:params:scim:api:messages:2.0:ListResponse"
      totalResults:
        type: number
      Resources:
        type: array
        items:
          allOf:
          - type: object
            properties:
              schemas:
                type: array
                items:
                  type: string
                  enum:
                  - "urn:ietf:params:scim:schemas:core:2.0:ResourceType"
              id:
                type: string
              name:
                type: string
              description:
                type: string
              endpoint:
                type: string
          - $ref: '#/definitions/meta'
  meta:
    type: object
    properties:
      meta:
        type: object
        properties:
          resourceType:
            type: string
          location:
            type: string
  messages:
    type: object
    properties:
      "urn:pingidentity:schemas:configuration:messages:2.0":
        type: object
        properties:
          notifications:
            type: array
            items:
              type: string
          requiredActions:
            type: array
            items:
              type: object
              properties:
                property:
                  type: string
                type:
                  type: string
                synopsis:
                  type: string
              required:
              - type
              - synopsis
  patch-request:
    type: object
    properties:
      operations:
        type: array
        items:
          $ref: '#/definitions/operation'
    required:
    - operations
  operation:
    type: object
    properties:
      op:
        type: string
        enum:
        - "add"
        - "remove"
        - "replace"
      path:
        type: string
      value:
        type: string
    required:
    - op
    - path
  attribute-syntax-list-response:
    type: object
    properties:
      schemas:
        type: array
        minItems: 1
        maxItems: 1
        items:
          type: string
          enum:
          - "urn:ietf:params:scim:api:messages:2.0:ListResponse"
      totalResults:
        type: number
      Resources:
        type: array
        items:
          $ref: '#/definitions/attribute-syntax-response'
    required:
    - schemas
    - totalResults
  add-attribute-syntax-request:
    allOf:
    - type: object
      properties:
        syntaxName:
          type: string
          description: >-
              Name of the new Attribute Syntax
    - $ref: '#/definitions/attribute-syntax-properties'
    required:
    - syntaxName
  attribute-syntax-response:
    allOf:
    - type: object
      properties:
        id:
          type: string
          description: >-
              Name of the Attribute Syntax
    - $ref: '#/definitions/meta'
    - $ref: '#/definitions/attribute-syntax-properties'
    required:
    - id
    - schemas
  attribute-syntax-response-with-messages:
    allOf:
    - $ref: '#/definitions/messages'
    - $ref: '#/definitions/attribute-syntax-response'
  attribute-syntax-properties:
    type: object
    properties:
      schemas:
        type: array
        minItems: 1
        maxItems: 1
        items:
          type: string
          enum:
          - "urn:pingidentity:schemas:configuration:2.0:attribute-syntax:attribute-type-description"
          - "urn:pingidentity:schemas:configuration:2.0:attribute-syntax:directory-string"
          - "urn:pingidentity:schemas:configuration:2.0:attribute-syntax:telephone-number"
          - "urn:pingidentity:schemas:configuration:2.0:attribute-syntax:distinguished-name"
          - "urn:pingidentity:schemas:configuration:2.0:attribute-syntax:generalized-time"
          - "urn:pingidentity:schemas:configuration:2.0:attribute-syntax:integer"
          - "urn:pingidentity:schemas:configuration:2.0:attribute-syntax:uuid"
          - "urn:pingidentity:schemas:configuration:2.0:attribute-syntax:generic"
          - "urn:pingidentity:schemas:configuration:2.0:attribute-syntax:json-object"
          - "urn:pingidentity:schemas:configuration:2.0:attribute-syntax:user-password"
          - "urn:pingidentity:schemas:configuration:2.0:attribute-syntax:boolean"
          - "urn:pingidentity:schemas:configuration:2.0:attribute-syntax:hex-string"
          - "urn:pingidentity:schemas:configuration:2.0:attribute-syntax:bit-string"
          - "urn:pingidentity:schemas:configuration:2.0:attribute-syntax:ldap-url"
          - "urn:pingidentity:schemas:configuration:2.0:attribute-syntax:name-and-optional-uid"
      strictFormat:
        type: boolean
        description: >-
               Indicates whether to require telephone number values to strictly comply with the standard definition for this syntax.
      requireBinaryTransfer:
        type: boolean
        description: >-
               Indicates whether values of this attribute are required to have a "binary" transfer option as described in RFC 4522. Attributes with this syntax will generally be referenced with names including ";binary" (e.g., "userCertificate;binary").
      allowZeroLengthValues:
        type: boolean
        description: >-
               Indicates whether zero-length (that is, an empty string) values are allowed.
      excludeAttributeFromCompaction:
        type: array
        items:
          type: string
        description: >-
               Specifies the specific attributes (which should be associated with this syntax) whose values should not be compacted. If one or more exclude attributes are specified, then values of those attributes will not have their values compacted. This property takes precedence over the include-attribute-in-compaction property.
      enableCompaction:
        type: boolean
        description: >-
               Indicates whether values of attributes with this syntax should be compacted when stored in a local DB database.
      stripSyntaxMinUpperBound:
        type: boolean
        description: >-
               Indicates whether the suggested minimum upper bound appended to an attribute's syntax OID in its schema definition Attribute Type Description should be stripped.
      includeAttributeInCompaction:
        type: array
        items:
          type: string
        description: >-
               Specifies the specific attributes (which should be associated with this syntax) whose values should be compacted. If one or more include attributes are specified, then only those attributes will have their values compacted. If not set then all attributes will have their values compacted. The exclude-attribute-from-compaction property takes precedence over this property.
      enabled:
        type: boolean
        description: >-
               Indicates whether the Attribute Syntax is enabled.


